sudo: required
services:
- docker
language: generic
env:
  global:
  - USER="ulysse.vautier"
  - ORGANIZATION="Rob-Orb"
  - EMAIL="ulysse.vautier@gmail.com"
  - REPO="rob-orb.github.io"
  - GH_REPO="github.com/${ORGANIZATION}/${REPO}.git"
  - secure: LiuqdaHEWxShp5obZmUOOS0k5BaRSfhK8KvDfVzFpF9l5CTSFmzkxO3t2bVv3m8Ag1HgchGmHXxdGRvpNCWrF8m6gd9BSmMJu173BU2KIvSsCozZklnR8D7QV2DAJ4kaTWDRT+X9SQDhxiaGvOoxCZjv9f48mSKMQhP9BZiixYOYmhFA4BcOV2dxITT4h0oCo2AI27/LDeXvUcFwNhT5ubx6sNLTq3zGX7huLIbJqBTD4rgfXvHGcBOFVRPl+4phT3QmXR6WipMsubFsCoVjU7sAuy18eFAgjBM7/JtttlpCviubtjkemsQVkCBdwRqFwUkIWOP7QFlHgc/4xetNpnHUWVLIcwj7oBBic1Q7Ad1P3/gi59pZTIXh2To736GUH8AQZgdrO7bw3h14PO1aIt+t8C4EiyPpmZzJDIRsVsGJ+zMt25gvVXAzif6tg7CtQ41KPaVTRSHP4up4fO0UkK3NOQaoda2VY+zH/6cUx/x3gxXzHHZm1F10X3+fPnxBSzmQ0wI9wygh55j9wSj9ghYCKaI5nniF5IrHem2F+cfSvNIpNuw8oPRFopgGxjiQx6AbI6Zcqo9YpHdG7bxeUcUYtfZ5mmLiws/KN69MtaezYScNhd2gUtpiZNiKJRCOTdD4zG2JCp75EVdFfmmct4iC5pPb7XGviQ9rInrz2tw=
  - secure: JR1aszUJIkVVCMpWD2RDt0LkP96CbrwsSwId1SfgmQKPeK42BzocFZT/JxvTbes4h3RSTPKsLFmYkfiOpck0vN659riryGAjqhCztwHcvawPIF5gCFnqEh6NNBS7bsS3aVKQoQAU+r4cmUPhfFWhsmDOg6dUQNM8XhTh9WezLjQQgu/xalqtb8XKSW831JKAZMYrwhaSznm5Eqw6aaQXWmuT/IIkJjfJNV59F2VtLtbnwgDLziwkz3t8uV7sj1ev8GXFDEHzpmHQ3i0be2INO+LIfgCgGJuBcsOsiRXcHuS+fRcFtzBTYe1WzrmUwxfBnx7s+9eKJXaFwgWB20NvN2paoPffQKt/7FKd2BUPUVuqmLR1DL8tsYmLzWtrgjxJA+kPzpB8S1GIKWIBcYo5RnKewQE6KB+3PIHVxucxyX9PhKbS51swSrnWxsxHSgFB73gKWGtD9WR7LTPiGSCMwN2ngGPyhZVSyvzFEReesyEY+2YkC5sVN5aCRQbDPlTFP32dLpG3alvYPjoEgMtq+ydwTQDMoDFWlenN48KiTPJjBfV77fa8JuYia8o52iyKGcB8AOt7Xj6U4nN6LHEHGlc1YybKfiIU3F03JZWjh5XyJzYS4QFuFG6Y6lbHL59NAkIM6tdKFTbZ3oqWRBs0h43rU+Opwq9IPvhP5YqPR1A=
before_install:
- openssl aes-256-cbc -K $encrypted_c4ae961d1455_key -iv $encrypted_c4ae961d1455_iv
  -in private.asc.enc -out private.asc -d
- sudo apt-get update
- sudo apt install -y qemu-system-arm qemu-user-static git reprepro gnupg
- gpg --allow-secret-key-import --import private.asc
- docker pull roborb/soft
- docker run -t -d --rm --name roborb-soft -v ${PWD}/../:/var/tmp roborb/soft
- docker exec -it roborb-soft /bin/bash
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu stretch main" > /etc/apt/sources.list.d/ros-latest.list'
- sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
- sudo apt update
- sudo apt upgrade
- sudo apt-get install build-essential python-yaml cmake subversion wget python-setuptools
  mercurial git-core libapr1-dev libaprutil1-dev libbz2-dev python-dev libgtest-dev
  python-paramiko libboost-all-dev liblog4cxx10-dev pkg-config python-empy swig python-nose
  lsb-release python-pip python-gtk2
- sudo pip install rosdep rosinstall_generator wstool rosinstall
- sudo rosdep init
- rosdep update
- mkdir catkin_ws
- cd catkin_ws
- rosinstall_generator ros_comm --rosdistro kinetic --deps --wet-only --exclude roslisp
  --tar > kinetic-ros_comm-wet.rosinstall
- wstool init src kinetic-ros_comm-wet.rosinstall
- rosdep install --from-paths src --ignore-src --rosdistro kinetic -y -r --os=debian:stretch
script:
- echo "###################################"
after_success:
- MESSAGE=$(git log --format=%B -n 1)${TRAVIS_COMMIT}
- cd ../
- git clone git://${GH_REPO}
- cd ${REPO}
- reprepro -b debian/ includedeb stretch ../*.deb
- git status
- git remote
- git config user.email ${EMAIL}
- git config user.name ${USER}
- git add .
- git commit -m "${MESSAGE}"
- git push "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
