sudo: required
services:
- docker
language: generic
env:
  global:
  - USER="ulysse.vautier"
  - ORGANIZATION="Rob-Orb"
  - EMAIL="ulysse.vautier@gmail.com"
  - REPO="rob-orb.github.io"
  - GH_REPO="github.com/${ORGANIZATION}/${REPO}.git"
  - secure: amqeJl1xat462o+X1CunZDdrelwpo9ee4Pp2fnTSZ+sXdAuW9sk1Hxd+hwm0Hnp0X4BQJU5kuuWZqSeVzSz7Xe7+vskHZeVAQO0xqx4OjcnYHDfefSPQYFZ5zyDkUvo5jJzX85E1l4EKHno5ayKv/bjCFu3aUEQQdyQ0f7nYecvSEZWPPSsv97MGnT4MuaklYEq0ViOXBnLPsfCeNhvjeuaH9JkGSbLGc6Os60CKGLgTyZL1fE4ok8Ix1eTYCDUwPuiEEKqDcTeazQ2jcCEGiYi8ur6jdArdhLlACCbMHNvGO3mJae4tKcVJiEh0MPzwx84/JsP8cpKwv5CLudKnGfTYeOXczl//AEilo2gWcr5Q6vbyCN/T2cLvqWlDV+L5OLD9+n6y09/Wcu59M5xmQAuiuad2MWvOSU+9s8/hw/JEELUUgfJw/EnkIAS4WULrgumy0bLA3zFdSBoh19c2/A2JJJ5WNX0IZh60Tdtkiqa9qhk9aQ9Zm7RlGtFlA/j2+oVd4/+zyeoc2tx4vC1H80iB7F73A+4msWq6sCsQHdRbsVMchYJ0KkXTJIbBLeozKq6bFmBR5ltMY8kXyTZtHWgWrqZ1u5je6l0sXGWy5c2rrXSyJWIS4RpQZoDhVOFn6HXSAU7vXYQQBzfV7YTfI+rjivRUpAJsGNBxLlURnxw=
before_install:
- openssl aes-256-cbc -K $encrypted_c4ae961d1455_key -iv $encrypted_c4ae961d1455_iv
  -in private.asc.enc -out private.asc -d
- sudo apt-get update
- sudo apt install -y qemu-system-arm qemu-user-static git reprepro gnupg
- gpg --allow-secret-key-import --import private.asc
- docker pull roborb/soft
- docker run -t -d --rm --name roborb-soft -v ${PWD}/../:/var/tmp roborb/soft
script:
- docker exec -i roborb-soft bash -c 'echo "deb http://packages.ros.org/ros/ubuntu stretch
  main" > /etc/apt/sources.list.d/ros-latest.list && 
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key
  421C365BD9FF1F717815A3895523BAEEB01FA116 &&
  apt update &&
  apt upgrade &&
  apt-get install build-essential python-yaml cmake subversion &&
  wget python-setuptools mercurial git-core libapr1-dev libaprutil1-dev libbz2-dev
  python-dev libgtest-dev python-paramiko libboost-all-dev liblog4cxx10-dev pkg-config python-empy swig python-nose lsb-release python-pip python-gtk2 &&
  pip install rosdep rosinstall_generator wstool rosinstall &&
  rosdep init &&
  rosdep update &&
  mkdir catkin_ws &&
  cd catkin_ws &&
  rosinstall_generator ros_comm --rosdistro kinetic --deps
  --wet-only --exclude roslisp --tar > kinetic-ros_comm-wet.rosinstall &&
  wstool init src kinetic-ros_comm-wet.rosinstall &&
  rosdep install --from-paths src --ignore-src --rosdistro kinetic -y -r --os=debian:stretch'
- echo "###################################"
after_success:
- MESSAGE=$(git log --format=%B -n 1)${TRAVIS_COMMIT}
- cd ../
- git clone git://${GH_REPO}
- cd ${REPO}
- reprepro -b debian/ includedeb stretch ../*.deb
- git status
- git remote
- git config user.email ${EMAIL}
- git config user.name ${USER}
- git add .
- git commit -m "${MESSAGE}"
- git push "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
